# Generated by Django 3.2.6 on 2021-08-23 16:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.band_image_file_path),
        ),
    ]
